<?php

namespace Database\Seeders;

use App\Enums\ProductAvailability;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class DemoProductSeeder extends Seeder
{
    public function run(): void
    {
        $brands = [
            ['name' => 'Shiseido', 'slug' => 'shiseido'],
            ['name' => 'Sony', 'slug' => 'sony'],
            ['name' => 'Rohto', 'slug' => 'rohto'],
            ['name' => 'Nintendo', 'slug' => 'nintendo'],
            ['name' => 'Pixy', 'slug' => 'pixy'],
            ['name' => 'Bourbon', 'slug' => 'bourbon'],
            ['name' => 'Kao', 'slug' => 'kao'],
            ['name' => 'Mandom', 'slug' => 'mandom'],
            ['name' => 'Kose', 'slug' => 'kose'],
            ['name' => 'Suntory', 'slug' => 'suntory'],
            ['name' => 'Morinaga', 'slug' => 'morinaga'],
            ['name' => 'DHC', 'slug' => 'dhc'],
            ['name' => 'Curel', 'slug' => 'curel'],
            ['name' => 'Fancl', 'slug' => 'fancl'],
            ['name' => 'Sido Muncul', 'slug' => 'sido-muncul'],
        ];

        $brandModels = [];
        foreach ($brands as $b) {
            $brandModels[$b['slug']] = Brand::firstOrCreate(['slug' => $b['slug']], $b);
        }

        $categories = [
            ['name' => 'Elektronik', 'slug' => 'elektronik'],
            ['name' => 'Fashion', 'slug' => 'fashion'],
            ['name' => 'Kesehatan', 'slug' => 'kesehatan'],
        ];

        $categoryModels = [];
        foreach ($categories as $c) {
            $categoryModels[$c['slug']] = Category::firstOrCreate(['slug' => $c['slug']], $c);
        }

        $skincare = Category::where('slug', 'skincare-beauty')->first() ?? $categoryModels['kesehatan'];
        $snack = Category::where('slug', 'snack-cemilan')->first() ?? Category::first();
        $minuman = Category::where('slug', 'minuman')->first() ?? Category::first();
        $bumbu = Category::where('slug', 'bumbu-dapur')->first() ?? Category::first();
        $indofood = Brand::where('slug', 'indofood')->first() ?? Brand::first();
        $nestle = Brand::where('slug', 'nestle')->first() ?? Brand::first();

        $products = [
            [
                'name' => 'Shiseido Sunscreen SPF50+',
                'slug' => 'shiseido-sunscreen-spf50',
                'sku' => 'SHI-SUN-50',
                'description' => 'Sunscreen waterproof terbaik dari Shiseido Tokyo.',
                'brand_id' => $brandModels['shiseido']->id,
                'category_id' => $skincare->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 320000,
                'discount_price' => 185000,
                'stock' => 45,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => true,
                'flash_sale_start_at' => now()->subDay(),
                'flash_sale_end_at' => now()->addDays(3),
                'weight_gram' => 100,
                'img' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Sony WH-1000XM5 Headphone',
                'slug' => 'sony-wh-1000xm5-headphone',
                'sku' => 'SNY-WH-1000',
                'description' => 'Flagship Wireless Noise Cancelling Headphones dari Sony Japan.',
                'brand_id' => $brandModels['sony']->id,
                'category_id' => $categoryModels['elektronik']->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 2100000,
                'discount_price' => 1250000,
                'stock' => 15,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => true,
                'flash_sale_start_at' => now()->subDay(),
                'flash_sale_end_at' => now()->addDays(3),
                'weight_gram' => 500,
                'img' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Kit Kat Matcha 10pcs',
                'slug' => 'kit-kat-matcha-10pcs',
                'sku' => 'KIT-MAT-10',
                'description' => 'KitKat cokelat matcha khas Uji Kyoto edisi Jepang.',
                'brand_id' => $nestle->id,
                'category_id' => $snack->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 110000,
                'discount_price' => 89000,
                'stock' => 60,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 150,
                'img' => 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Hada Labo Lotion 200ml',
                'slug' => 'hada-labo-lotion-200ml',
                'sku' => 'HDL-LOT-200',
                'description' => 'Hydrating lotion dengan hyaluronic acid premium.',
                'brand_id' => $brandModels['rohto']->id,
                'category_id' => $skincare->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 175000,
                'discount_price' => 145000,
                'stock' => 30,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 250,
                'img' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Nintendo Switch OLED Model',
                'slug' => 'nintendo-switch-oled-model',
                'sku' => 'NTD-SWI-OLED',
                'description' => 'Konsol game portabel layar OLED 7 inci Japan Version.',
                'brand_id' => $brandModels['nintendo']->id,
                'category_id' => $categoryModels['elektronik']->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 4200000,
                'discount_price' => 3400000,
                'stock' => 10,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 1200,
                'img' => 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Pixy CC Cushion SPF30',
                'slug' => 'pixy-cc-cushion-spf30',
                'sku' => 'PIX-CC-30',
                'description' => 'Cushion ringan natural look dengan proteksi UV.',
                'brand_id' => $brandModels['pixy']->id,
                'category_id' => $skincare->id,
                'origin_country' => 'ID',
                'currency' => 'IDR',
                'price' => 175000,
                'discount_price' => null,
                'stock' => 50,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 100,
                'img' => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Bourbon Alfort Choco',
                'slug' => 'bourbon-alfort-choco',
                'sku' => 'BRB-ALF-01',
                'description' => 'Biskuit gandum bersalut cokelat susu khas Jepang.',
                'brand_id' => $brandModels['bourbon']->id,
                'category_id' => $snack->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 58000,
                'discount_price' => null,
                'stock' => 40,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 120,
                'img' => 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Salonpas Pain Relief Patch',
                'slug' => 'salonpas-pain-relief-patch',
                'sku' => 'SLP-PAT-20',
                'description' => 'Koyo pereda nyeri otot dan pegal langsung dari Jepang.',
                'brand_id' => $brandModels['kao']->id,
                'category_id' => $categoryModels['kesehatan']->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 42000,
                'discount_price' => null,
                'stock' => 80,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 60,
                'img' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Makarizo Hair Sachet',
                'slug' => 'makarizo-hair-sachet',
                'sku' => 'MKR-HAI-01',
                'description' => 'Perawatan rambut praktis bernutrisi tinggi.',
                'brand_id' => $indofood->id,
                'category_id' => $skincare->id,
                'origin_country' => 'ID',
                'currency' => 'IDR',
                'price' => 65000,
                'discount_price' => 45000,
                'stock' => 100,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 50,
                'img' => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Gatsby Hair Wax',
                'slug' => 'gatsby-hair-wax',
                'sku' => 'GTB-WAX-80',
                'description' => 'Styling pomade & wax tahan lama dari Mandom.',
                'brand_id' => $brandModels['mandom']->id,
                'category_id' => $skincare->id,
                'origin_country' => 'ID',
                'currency' => 'IDR',
                'price' => 125000,
                'discount_price' => 89000,
                'stock' => 70,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 90,
                'img' => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Kose Suncut Spray',
                'slug' => 'kose-suncut-spray',
                'sku' => 'KOS-SNC-90',
                'description' => 'Sunscreen spray praktis perlindungan maksimal UV SPF50+.',
                'brand_id' => $brandModels['kose']->id,
                'category_id' => $skincare->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 180000,
                'discount_price' => 125000,
                'stock' => 35,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 150,
                'img' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Suntory Oolong Tea',
                'slug' => 'suntory-oolong-tea',
                'sku' => 'SNT-OOL-500',
                'description' => 'Teh Oolong asli Jepang tanpa gula kemasan botol.',
                'brand_id' => $brandModels['suntory']->id,
                'category_id' => $minuman->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 95000,
                'discount_price' => 67000,
                'stock' => 50,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 550,
                'img' => 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Morinaga Caramel Box',
                'slug' => 'morinaga-caramel-box',
                'sku' => 'MRN-CAR-12',
                'description' => 'Permen karamel legendaris Jepang sejak 1913.',
                'brand_id' => $brandModels['morinaga']->id,
                'category_id' => $snack->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 55000,
                'discount_price' => 34000,
                'stock' => 65,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 100,
                'img' => 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Pino Ice Cream Kit',
                'slug' => 'pino-ice-cream-kit',
                'sku' => 'PIN-ICE-06',
                'description' => 'Snack cokelat ice cream bite favorit keluarga di Jepang.',
                'brand_id' => $brandModels['morinaga']->id,
                'category_id' => $snack->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 130000,
                'discount_price' => 88000,
                'stock' => 20,
                'availability_type' => ProductAvailability::OPEN_PO,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 180,
                'img' => 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Biore UV Aqua Gel',
                'slug' => 'biore-uv-aqua-gel',
                'sku' => 'BIO-AQU-90',
                'description' => 'Tabir surya tekstur seringan air dengan formula micro defense.',
                'brand_id' => $brandModels['kao']->id,
                'category_id' => $skincare->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 160000,
                'discount_price' => 112000,
                'stock' => 40,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 90,
                'img' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Kao Merries Diaper S',
                'slug' => 'kao-merries-diaper-s',
                'sku' => 'KAO-MER-S',
                'description' => 'Popok bayi premium Jepang sirkulasi udara maksimal.',
                'brand_id' => $brandModels['kao']->id,
                'category_id' => $categoryModels['kesehatan']->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 310000,
                'discount_price' => 235000,
                'stock' => 25,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 1400,
                'img' => 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Mandom Barrier Repair',
                'slug' => 'mandom-barrier-repair',
                'sku' => 'MND-BAR-05',
                'description' => 'Masker wajah hydrating sheet mask dengan serum pelembab intensif.',
                'brand_id' => $brandModels['mandom']->id,
                'category_id' => $skincare->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 110000,
                'discount_price' => 78000,
                'stock' => 50,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 120,
                'img' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'DHC Deep Cleansing Oil',
                'slug' => 'dhc-deep-cleansing-oil',
                'sku' => 'DHC-DCO-200',
                'description' => 'Minyak pembersih wajah berbahan dasar zaitun murni khas Tokyo.',
                'brand_id' => $brandModels['dhc']->id,
                'category_id' => $skincare->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 275000,
                'discount_price' => 195000,
                'stock' => 35,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 220,
                'img' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Curel Lotion 400ml',
                'slug' => 'curel-lotion-400ml',
                'sku' => 'CRL-LOT-400',
                'description' => 'Moisture lotion intensif untuk kulit sensitif dan kering.',
                'brand_id' => $brandModels['curel']->id,
                'category_id' => $skincare->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 210000,
                'discount_price' => 145000,
                'stock' => 30,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 450,
                'img' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Fancl Mild Cleansing Oil',
                'slug' => 'fancl-mild-cleansing-oil',
                'sku' => 'FNC-MCL-120',
                'description' => 'Pembersih makeup lembut tanpa pengawet nomor 1 di Jepang.',
                'brand_id' => $brandModels['fancl']->id,
                'category_id' => $skincare->id,
                'origin_country' => 'JP',
                'currency' => 'IDR',
                'price' => 145000,
                'discount_price' => 98000,
                'stock' => 45,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 160,
                'img' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Tolak Angin Sido Muncul Box',
                'slug' => 'tolak-angin-sido-muncul-box',
                'sku' => 'SDM-TLK-12',
                'description' => 'Herbal cair pereda masuk angin khas nusantara 12 sachet.',
                'brand_id' => $brandModels['sido-muncul']->id,
                'category_id' => $categoryModels['kesehatan']->id,
                'origin_country' => 'ID',
                'currency' => 'IDR',
                'price' => 48000,
                'discount_price' => 42000,
                'stock' => 120,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 200,
                'img' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&fit=crop&q=80',
            ],
            [
                'name' => 'Kopi Luwak White Koffie Bag',
                'slug' => 'kopi-luwak-white-koffie-bag',
                'sku' => 'LWK-WHT-10',
                'description' => 'Kopi instan premium white koffie rendah asam di lambung.',
                'brand_id' => $indofood->id,
                'category_id' => $minuman->id,
                'origin_country' => 'ID',
                'currency' => 'IDR',
                'price' => 32000,
                'discount_price' => 26000,
                'stock' => 85,
                'availability_type' => ProductAvailability::READY_STOCK,
                'is_active' => true,
                'is_flash_sale' => false,
                'weight_gram' => 220,
                'img' => 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=400&fit=crop&q=80',
            ],
        ];

        foreach ($products as $pData) {
            $img = $pData['img'];
            unset($pData['img']);
            $prod = Product::firstOrCreate(['slug' => $pData['slug']], $pData);
            ProductImage::firstOrCreate(
                ['product_id' => $prod->id],
                ['path' => $img, 'order' => 0, 'is_primary' => true]
            );
        }
    }
}
